"""Configuration helpers for Azure resources."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any


LOCAL_SECRETS_PATH = Path(__file__).parent.parent / ".streamlit" / "secrets.toml"
CONFIG_SECRET_KEYS = (
    "azure_endpoint",
    "azure_api_key",
    "storage_container_url",
    "storage_connection_string",
    "storage_container_name",
    "custom_model_id",
)


@dataclass
class AzureConfig:
    endpoint: str = ""
    api_key: str = ""
    storage_container_url: str = ""
    storage_connection_string: str = ""
    storage_container_name: str = ""
    custom_model_id: str = ""

    @property
    def has_document_intelligence(self) -> bool:
        return bool(self.endpoint and self.api_key)

    @property
    def has_storage(self) -> bool:
        return bool(
            self.storage_container_url
            or (self.storage_connection_string and self.storage_container_name)
        )


def _secret_value(name: str, default: str = "") -> str:
    try:
        import streamlit as st

        return str(st.secrets.get(name, default))
    except Exception:
        return default


def _session_value(name: str, default: str = "") -> str:
    try:
        import streamlit as st

        return str(st.session_state.get(name, default))
    except Exception:
        return default


def _read_setting(session_key: str, env_key: str, secret_key: str) -> str:
    return (
        _session_value(session_key)
        or os.getenv(env_key, "")
        or _secret_value(secret_key)
    ).strip()


def get_azure_config() -> AzureConfig:
    """Read Azure config from Streamlit session, env vars, or secrets."""

    return AzureConfig(
        endpoint=_read_setting(
            "azure_endpoint", "DOCUMENTINTELLIGENCE_ENDPOINT", "azure_endpoint"
        ),
        api_key=_read_setting(
            "azure_api_key", "DOCUMENTINTELLIGENCE_API_KEY", "azure_api_key"
        ),
        storage_container_url=_read_setting(
            "storage_container_url",
            "AZURE_STORAGE_CONTAINER_URL",
            "storage_container_url",
        ),
        storage_connection_string=_read_setting(
            "storage_connection_string",
            "AZURE_STORAGE_CONNECTION_STRING",
            "storage_connection_string",
        ),
        storage_container_name=_read_setting(
            "storage_container_name",
            "AZURE_STORAGE_CONTAINER_NAME",
            "storage_container_name",
        ),
        custom_model_id=_read_setting(
            "custom_model_id", "DOCUMENTINTELLIGENCE_CUSTOM_MODEL_ID", "custom_model_id"
        ),
    )


def write_local_secrets(
    config: AzureConfig,
    path: Path | None = None,
) -> Path:
    """Persist Azure configuration to a local Streamlit secrets file."""

    target = path or LOCAL_SECRETS_PATH
    existing = _read_local_toml(target)
    existing.update(
        {
            "azure_endpoint": config.endpoint.strip(),
            "azure_api_key": config.api_key.strip(),
            "storage_container_url": config.storage_container_url.strip(),
            "storage_connection_string": config.storage_connection_string.strip(),
            "storage_container_name": config.storage_container_name.strip(),
            "custom_model_id": config.custom_model_id.strip(),
        }
    )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(_dump_toml(existing), encoding="utf-8")
    return target


def _read_local_toml(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}

    try:
        import tomllib

        with open(path, "rb") as f:
            data = tomllib.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _dump_toml(values: dict[str, Any]) -> str:
    config_items = {
        key: values.get(key, "")
        for key in CONFIG_SECRET_KEYS
        if key in values
    }
    other_items = {
        key: value
        for key, value in values.items()
        if key not in CONFIG_SECRET_KEYS
    }
    other_scalars = {
        key: value for key, value in other_items.items() if not isinstance(value, dict)
    }
    other_tables = {
        key: value for key, value in other_items.items() if isinstance(value, dict)
    }

    lines = [
        "# Local Streamlit secrets. Do not commit this file.",
        "# Generated by the Azure Document Intelligence Studio-Core app.",
        "",
    ]
    lines.extend(_dump_toml_items(config_items))
    if other_scalars or other_tables:
        lines.append("")
        lines.append("# Other existing secrets")
        lines.extend(_dump_toml_items(other_scalars))
        if other_scalars and other_tables:
            lines.append("")
        lines.extend(_dump_toml_items(other_tables))
    return "\n".join(lines).rstrip() + "\n"


def _dump_toml_items(values: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for key, value in values.items():
        if isinstance(value, dict):
            lines.append(f"[{key}]")
            lines.extend(_dump_toml_items(value))
            lines.append("")
        else:
            lines.append(f"{key} = {_toml_value(value)}")
    return lines


def _toml_value(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    return json.dumps("" if value is None else str(value))


def redact(value: str, keep: int = 4) -> str:
    """Return a safe display version of a secret-like string."""

    if not value:
        return ""
    if len(value) <= keep:
        return "*" * len(value)
    return f"{value[:keep]}...{value[-keep:]}"
